# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_status.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ServerRequest" do
    optional :name, :string, 1
  end
  add_message "DiskStatus" do
    optional :total, :string, 1
  end
end

ServerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ServerRequest").msgclass
DiskStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("DiskStatus").msgclass
