# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_status.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "server.Empty" do
  end
  add_message "server.DiskStatus" do
    optional :total, :string, 1
  end
end

module Server
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.Empty").msgclass
  DiskStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("server.DiskStatus").msgclass
end
