# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: server_status.proto for package 'server'

require 'grpc'
require 'server_status_pb'

module Server
  module Status
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'server.Status'

      rpc :HandleRequest, Empty, DiskStatus
    end

    Stub = Service.rpc_stub_class
  end
end
